# Generated by Django 3.2.11 on 2022-03-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ntk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passanger',
            name='ntk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
