# Generated by Django 3.2.11 on 2022-03-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0002_auto_20220317_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dropout_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropout_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ride_pin',
            name='dropout_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ride_pin',
            name='dropout_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ride_pin',
            name='pickup_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ride_pin',
            name='pickup_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='active_ac_with_otp',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Deactive'), ('2', 'Forget')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='passanger',
            name='active_ac_with_otp',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Deactive'), ('2', 'Forget')], default='0', max_length=10),
        ),
    ]
