# Generated by Django 3.2.11 on 2022-03-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0003_auto_20220317_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='username',
        ),
        migrations.RemoveField(
            model_name='passanger',
            name='username',
        ),
        migrations.AddField(
            model_name='booking',
            name='dropout_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropout_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='active_ac_with_otp',
            field=models.CharField(choices=[('1', 'Verified'), ('0', 'Not Verified'), ('2', 'Forget')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='passanger',
            name='active_ac_with_otp',
            field=models.CharField(choices=[('1', 'Verified'), ('0', 'Not Verified'), ('2', 'Forget')], default='0', max_length=10),
        ),
    ]
