# Generated by Django 3.2.11 on 2022-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0003_auto_20220408_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='publish',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('2', 'BLOCK USER')], default=0, max_length=20),
        ),
    ]
