# Generated by Django 3.2.11 on 2022-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0004_auto_20220317_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='traveling_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
