# Generated by Django 3.2.11 on 2022-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0004_alter_ride_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
