# Generated by Django 3.2.11 on 2022-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0005_ride_ride_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
