# Generated by Django 3.2.11 on 2022-04-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0006_alter_ride_ride_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers_rating',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='drivers_rating',
            name='passengerid',
        ),
        migrations.RemoveField(
            model_name='drivers_rating',
            name='tri',
        ),
        migrations.RemoveField(
            model_name='passenger_rating',
            name='driverid',
        ),
        migrations.RemoveField(
            model_name='passenger_rating',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='passenger_rating',
            name='tri',
        ),
        migrations.RemoveField(
            model_name='passenger_report',
            name='driverid',
        ),
        migrations.RemoveField(
            model_name='passenger_report',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='passenger_report',
            name='tri',
        ),
        migrations.DeleteModel(
            name='Driver_Report',
        ),
        migrations.DeleteModel(
            name='Drivers_Rating',
        ),
        migrations.DeleteModel(
            name='Passenger_Rating',
        ),
        migrations.DeleteModel(
            name='Passenger_Report',
        ),
    ]
