# Generated by Django 3.2.11 on 2022-04-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0007_auto_20220412_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(blank=True)),
                ('create', models.DateField(blank=True, null=True)),
                ('driverid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doxer.driver')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doxer.passanger')),
                ('tri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doxer.ride_pin')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rates', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('review', models.TextField(blank=True)),
                ('create', models.DateField(blank=True, null=True)),
                ('driverid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doxer.driver')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doxer.passanger')),
                ('tri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doxer.ride_pin')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rates', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True)),
                ('review', models.TextField(blank=True)),
                ('create', models.DateField(blank=True, null=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doxer.driver')),
                ('passengerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doxer.passanger')),
                ('tri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doxer.ride')),
            ],
        ),
        migrations.CreateModel(
            name='Driver_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(blank=True)),
                ('create', models.DateField(blank=True, null=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doxer.driver')),
                ('passengerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doxer.passanger')),
                ('tri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doxer.ride')),
            ],
        ),
    ]
