# Generated by Django 3.2.11 on 2022-03-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0007_alter_ride_pin_for_parcel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
