# Generated by Django 3.2.11 on 2022-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0008_driver_report_drivers_rating_passenger_rating_passenger_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
