# Generated by Django 3.2.11 on 2022-03-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0008_delete_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers_rating',
            name='tri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doxer.ride'),
        ),
    ]
