# Generated by Django 3.2.11 on 2022-03-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0010_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Drivers_documents/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='image2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Drivers_documents/'),
        ),
        migrations.AddField(
            model_name='passanger',
            name='image1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Passengers_documents/'),
        ),
        migrations.AddField(
            model_name='passanger',
            name='image2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Passengers_documents/'),
        ),
        migrations.AddField(
            model_name='passanger',
            name='img_status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
