# Generated by Django 3.2.11 on 2022-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0011_auto_20220325_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='img_status',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='passanger',
            name='img_status',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
