# Generated by Django 3.2.11 on 2022-03-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0013_auto_20220328_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passanger',
            name='image1',
            field=models.ImageField(blank=True, default='Passengers_documents/idproof.png', max_length=255, null=True, upload_to='Passengers_documents/'),
        ),
        migrations.AlterField(
            model_name='passanger',
            name='image2',
            field=models.ImageField(blank=True, default='Passengers_documents/idproof.png', max_length=255, null=True, upload_to='Passengers_documents/'),
        ),
    ]
