# Generated by Django 3.2.11 on 2022-03-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0018_auto_20220328_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_report',
            name='create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_report',
            name='tri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doxer.ride'),
        ),
        migrations.AlterField(
            model_name='drivers_rating',
            name='create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger_rating',
            name='create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger_report',
            name='create',
            field=models.DateField(blank=True, null=True),
        ),
    ]
