# Generated by Django 3.2.11 on 2022-03-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0020_ride_as_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='getpassenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doxer.passanger'),
        ),
    ]
