# Generated by Django 3.2.11 on 2022-03-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0021_ride_getpassenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='getdriver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doxer.driver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='getpassenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doxer.passanger'),
        ),
    ]
