# Generated by Django 3.2.11 on 2022-03-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0022_auto_20220329_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='gov_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='max_seat_in_back',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pet_allowed',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='smoke_allowed',
        ),
    ]
