# Generated by Django 3.2.11 on 2022-03-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0023_auto_20220329_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride_pin',
            name='mine_ride',
        ),
        migrations.AddField(
            model_name='ride_pin',
            name='getdriver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Driver', to='doxer.driver'),
        ),
        migrations.AddField(
            model_name='ride_pin',
            name='getpassenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Passanger', to='doxer.passanger'),
        ),
    ]
