# Generated by Django 3.2.11 on 2022-03-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0026_auto_20220329_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Id_proofe',
        ),
    ]
