# Generated by Django 3.2.11 on 2022-03-30 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0027_delete_id_proofe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_pin',
            name='getride1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Passenger', to='doxer.ride'),
        ),
        migrations.AlterField(
            model_name='ride_pin',
            name='getride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Driver', to='doxer.ride'),
        ),
    ]
