# Generated by Django 3.2.11 on 2022-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0029_ride_pin_as_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
