# Generated by Django 3.2.11 on 2022-04-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0030_ride_dtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dtime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ride',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ride_pin',
            name='ride_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
