# Generated by Django 3.2.11 on 2022-04-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0031_auto_20220404_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='traveling_time',
        ),
    ]
