# Generated by Django 3.2.11 on 2022-04-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0032_remove_ride_traveling_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='publish',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default=0, max_length=20),
        ),
    ]
