# Generated by Django 3.2.11 on 2022-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0033_ride_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dtime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
