# Generated by Django 3.2.11 on 2022-04-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0034_auto_20220404_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
