# Generated by Django 3.2.11 on 2022-04-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0035_ride_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_pin',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doxer.vehicle'),
        ),
    ]
