# Generated by Django 3.2.11 on 2022-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0038_driver_report_drivers_rating_passenger_rating_passenger_report_ride_ride_pin_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_pin',
            name='for_parcel',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ride_pin',
            name='for_passenger',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
