# Generated by Django 3.2.11 on 2022-04-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxer', '0041_auto_20220406_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
